version: "3"
services:
  mongodb:
    image: mongo:5.0.5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=develop
      - MONGO_INITDB_ROOT_PASSWORD=develop

  rabbitmq:
    image: rabbitmq:3.13.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=develop
      - RABBITMQ_DEFAULT_PASS=develop
