[tool.mypy]
plugins = [
    "pydantic.mypy"
]

mypy_path = "."
follow_imports = "normal"
warn_redundant_casts = true
disallow_any_generics = true
strict_equality = true
ignore_missing_imports = false
no_implicit_reexport = true
warn_unused_ignores = true
check_untyped_defs = true
disallow_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
